### ISSUE TITLE
Imgproxy v3 support?

### ISSUE THREAD

**Issue by arbiyanto** [crocodile2u/imgproxy-php#11]
It looks like this package is not working on Imgproxy v3. 

The URL on v3 is changing to something like this `http://imgproxy.example.com/AfrOrF3gWeDA6VOlDG4TzxMv39O7MXnF4CXpKUwGqRM/preset:sharp/resize:fill:300:400:0/gravity:sm/plain/http://example.com/images/curiosity.jpg@png
` 

while the old one is using slash for separating the options and already deprecated
`http://localhost:7001/owS6Nr5-M_ksJH0LGeNemRLmHEsexVrqdWLk0gZLhEU/fill/800/553/sm/0/bG9jYWw6Ly8vaW1hZ2VzL3Byb2R1Y3RzL2RldGFpbC9MTlpLOUZuSWprZzFiQnZNSWNneUJtNXdoenhiUzMzNUFHSExVdkNoLnBuZw.png`

**Comment by arbiyanto** [comment]
Looks like I just found out, we just need to change the mode to Advanced [https://github.com/imgproxy/imgproxy/blob/master/CHANGELOG.md#removed-1](Changelog)

**Comment by crocodile2u** [comment]
Sorry for responding a bit late on this. Thanks for reporting this, I will edit the README accordingly!
