### ISSUE TITLE
Do you have any plans to support the advanced URL params?

### ISSUE THREAD

**Issue by adampatterson** [crocodile2u/imgproxy-php#4]
Imgproxy will be removing the older URL params in favor of the newer "advanced" params.

https://github.com/imgproxy/imgproxy/discussions/681

Do you have any plans to support them?
https://docs.imgproxy.net/generating_the_url_advanced?id=example

Cheers!

**Comment by crocodile2u** [comment]
TBH, this project is no longer within the scope for me. I promise I'll take a look if it can be implemented fast. If not, it'll take time. PRs are much welcome, BTW.

**Comment by adampatterson** [comment]
No problem, If I get it working I will pass it on!

**Comment by crocodile2u** [comment]
I'm actually returning to this subject, and I think there will be so many changes that it's going to mark version 2.0.

**Comment by crocodile2u** [comment]
Because the code base is tiny atm, I think I'll keep it backwards compatible though.

**Comment by adampatterson** [comment]
@crocodile2u I'm still working to resolve the new URL format issues in my own implementation. I am not sure if it's the version I have installed but using their example directly doesn't seem to work for me.

And you seem to have the only composer package out there :)

**Comment by crocodile2u** [comment]
I started to work on this, you can check out the progress here: https://github.com/crocodile2u/imgproxy-php/tree/v2.x

**Question to all interested**: for the moment, I'm not adding any validation of processing options. This is for the sake of simplicity and speed. As far as I am concerned, the URL generation must be as fast as possible, and if I made a mistake with some parameter so that a processing option becomes invalid (like, negative width or dpr), then probably it's OK to just check on the resulting image. Do you think that adding validation for numbers and enums (like "resizing_type") is necessary?

**Comment by crocodile2u** [comment]
Additionally, I'm planning a **RC** for **v2.0** some 1-2 weeks later, so everyone can test it by modifying your composer file in this fashion:

```
{
    "require": {
        "crocodile2u/imgproxy-php": "2.0.*"
    },
    "minimum-stability": "RC",
    "prefer-stable": true
}
```

**Comment by crocodile2u** [comment]
v2 RC1 is out: https://github.com/crocodile2u/imgproxy-php/releases/tag/v2.0-RC1

It's fully backwards compatible. Please inform if you have any issues upgrading.

Also, checkout README in the new version: there are (limited) instructions on how to use the Advanced URL mode.

**Comment by adampatterson** [comment]
Hey @crocodile2u I installed 2.0RC but it looks like the code is from v1

Even after changing my minimum stability to RC.

Perhaps I am doing something wrong?

Composer File:
![image](https://user-images.githubusercontent.com/31537/133011483-1fd6e464-033c-42fd-8f19-d0053ac27b08.png)

Composer Lock:
![image](https://user-images.githubusercontent.com/31537/133011508-69b07590-8aa5-463b-bba8-08fbd16e9a5b.png)

The package only contains 3 files from the previous version.
![image](https://user-images.githubusercontent.com/31537/133011540-f6768146-4d8c-42d0-8e09-fddc13594f21.png)

**Comment by crocodile2u** [comment]
Strange, but that's probably me doing something wrong. Maybe that's because
i made a tag on a branch other then "master".. I'll check it out, thanks
for the report.

**Comment by crocodile2u** [comment]
Nah, it was exactly the opposite: I accidentally made that tag on master, and I only made sure that the new RC is installed following the instructions above, but never looked into the installed package itself. Should be fixed now, this time I also check that updated package is installed. To avoid composer cache getting in the way, I simply published RC2

**Comment by adampatterson** [comment]
I moved the source into the vendor folder and the older example worked but the advanced example gave me an invalid URL format.

I suspect this is my local ImgProxy version which is `/usr/local/Cellar/imgproxy/2.16.7/bin/imgproxy`

I will see if I can install the Docker version tonight

**Comment by crocodile2u** [comment]
The docker-compose file has the :latest imgproxy image. Can you by chance provided the code you use to get the URL? I will not need your imgproxy URL and/or KEY/SALT.

**Comment by crocodile2u** [comment]
> I moved the source into the vendor folder

You should be able to simply install the RC2 if you modify `composer.json`.

**Comment by adampatterson** [comment]
Hello @crocodile2u I used the example code:

```
 $builder = new UrlBuilder(config('services.img_proxy.url'), config('services.img_proxy.key', null), config('services.img_proxy.salt', null));

            // Generate imgproxy URL for an image, resizing to 300x200 with default settings (*)
            $url = $builder->build("https://www.adampatterson.ca/wp-content/themes/adam/assets/img/hero_center.jpg", 300, 200);

            echo "<img src='".$url->toString()."''>";
            echo "<hr>";
            echo $url->toString();
            echo "<hr>";

            // Customize URL params
            $url->setFit("fill")
                ->setWidth(1200)
                ->setHeight(1200)
                ->setGravity("no")
                ->setEnlarge(true);

            // switch to advanced URL mode with tons of extra features, superior to the basic mode:
            $url->useAdvancedMode();

            // set processing options:
            $url->options()->withResizingAlgorithm(ResizingAlgorithm::LINEAR)/* -> chain more with<FEATURE>() calls -> ... */;

            echo "<img src='".$url->toString()."''>";
            echo "<hr>";
            echo $url->toString();
```

**Comment by crocodile2u** [comment]
Yeah, I found out where this comes from. Certain processing options, like ResizingAlgorithm, are marked as "PRO" which means they are only available in the PRO version of imgproxy. If instead of `withResizingAlgorithm()` you use, say, `withDpr(2)` (or any other options not marked with PRO label), that generates correct output. I will definitely have to update the README, though, so the example does not use any PRO options, and will have to add a paragraph about PRO.

Thanks a ton for the detailed report!

**Comment by crocodile2u** [comment]
@adampatterson , I just have published RC3 with updated docs (and the example in docs). With the `darthsim/imgproxy:latest` docker image, example in the README works just fine. Can you confirm it's working for you?

**Comment by adampatterson** [comment]
Awesome, I will update over the next few days.

What really started my quest as blurring an image, is that possible with
the advanced features?

**Comment by crocodile2u** [comment]
According to
https://docs.imgproxy.net/generating_the_url_advance, blur is not a PRO
feature, you should be able to use it:

```php
$url->options()->withBlur(5);
```

**Comment by crocodile2u** [comment]
Well, I all tests are passing. Seemingly, there are no critical issues with the RC, and the backwards compatibility is maintained. I think tomorrow is a good day for a new release.

**Comment by adampatterson** [comment]
Awesome, that's exciting!

**Comment by crocodile2u** [comment]
Well... I kinda was under full impression that I made that release the next day.. Also had some things happening, and didn't check Github. Today I learned that actually I never filed the release of 2.0, so here we go: https://github.com/crocodile2u/imgproxy-php/releases/tag/v2.0.0 !
